"use client";

import { useEffect, useState } from "react";
import { Loader2, Plus, Save, Trash2 } from "lucide-react";
import DashboardLayout from "../../components/DashboardLayout";

type FaqItem = { q: string; a: string };
type Settings = { enabled: boolean; monthlyPrice: number; currency: string; title: string; description: string; features: string[]; terms: string[]; faq: FaqItem[]; primaryColor: string; secondaryColor: string };
const empty: Settings = { enabled: true, monthlyPrice: 2, currency: "USD", title: "أنشئ موقعك الخاص", description: "احصل على لوحة خدمات خاصة بك وابدأ بيع الخدمات وكسب العمولة.", features: ["تصميم احترافي قابل للتخصيص"], terms: ["اسم الفرع يجب أن يكون فريدًا ومتاحًا."], faq: [{ q: "ما هو الموقع الفرعي؟", a: "مساحة مستقلة باسمك داخل منصة Trendcom." }], primaryColor: "#f97316", secondaryColor: "#fbbf24" };

export default function AdminResellerSettingsPage() {
  const [form, setForm] = useState<Settings>(empty);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ text: string; error?: boolean } | null>(null);
  useEffect(() => { fetch("/api/admin/reseller-settings", { cache: "no-store" }).then((r) => r.json()).then((data) => { if (data.settings) setForm({ ...empty, ...data.settings }); else if (data.error) setMessage({ text: data.error, error: true }); }).catch(() => setMessage({ text: "تعذر تحميل الإعدادات", error: true })).finally(() => setLoading(false)); }, []);
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => setForm((previous) => ({ ...previous, [key]: value }));
  const updateList = (key: "features" | "terms", index: number, value: string) => update(key, form[key].map((item, itemIndex) => itemIndex === index ? value : item));
  const updateFaq = (index: number, key: keyof FaqItem, value: string) => update("faq", form.faq.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(null); try { const response = await fetch("/api/admin/reseller-settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "تعذر الحفظ"); setForm({ ...empty, ...data.settings }); setMessage({ text: "تم حفظ إعدادات المواقع بنجاح." }); } catch (error: unknown) { setMessage({ text: error instanceof Error ? error.message : "تعذر الحفظ", error: true }); } finally { setSaving(false); } };
  const inputClass = "w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2.5 text-sm text-white outline-none focus:border-[var(--color-primary)]";
  if (loading) return <DashboardLayout><div className="flex min-h-[40vh] items-center justify-center text-zinc-400"><Loader2 className="mr-2 animate-spin" size={20} /> جاري تحميل الإعدادات...</div></DashboardLayout>;
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-4xl space-y-4 pb-10"><div><h1 className="text-2xl font-black text-white">إعدادات المواقع الفرعية</h1><p className="mt-1 text-sm text-zinc-500">تحكم في السعر والمحتوى الذي يظهر للمستخدمين قبل طلب إنشاء الموقع.</p></div><form onSubmit={save} className="space-y-4">
    <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-card)] p-5"><div className="flex items-center justify-between"><div><h2 className="font-black text-white">حالة الخدمة والسعر</h2><p className="mt-1 text-xs text-zinc-500">هذا الإصدار يسجل الطلبات فقط؛ لا ينفذ خصمًا ماليًا حتى اكتمال نظام الإنشاء والعزل.</p></div><label className="flex items-center gap-2 text-sm font-bold text-zinc-300"><input type="checkbox" checked={form.enabled} onChange={(e) => update("enabled", e.target.checked)} /> مفعّلة</label></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="block"><span className="mb-1 block text-xs font-bold text-zinc-400">السعر الشهري</span><input className={inputClass} type="number" min="0" step="0.01" value={form.monthlyPrice} onChange={(e) => update("monthlyPrice", Number(e.target.value))} /></label><label className="block"><span className="mb-1 block text-xs font-bold text-zinc-400">العملة</span><input className={inputClass} maxLength={3} value={form.currency} onChange={(e) => update("currency", e.target.value.toUpperCase())} /></label></div></section>
    <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-card)] p-5"><h2 className="mb-4 font-black text-white">عنوان ووصف الصفحة</h2><div className="space-y-3"><input className={inputClass} value={form.title} onChange={(e) => update("title", e.target.value)} placeholder="عنوان الصفحة" /><textarea className={inputClass} rows={3} value={form.description} onChange={(e) => update("description", e.target.value)} placeholder="الوصف" /></div></section>
    <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-card)] p-5"><h2 className="mb-4 font-black text-white">الميزات والشروط</h2><div className="grid gap-5 sm:grid-cols-2">{(["features", "terms"] as const).map((key) => <div key={key}><div className="mb-2 flex items-center justify-between"><span className="text-sm font-bold text-zinc-300">{key === "features" ? "الميزات" : "الشروط"}</span><button type="button" onClick={() => update(key, [...form[key], ""])} className="rounded-lg bg-[var(--color-surface)] p-1.5 text-[var(--color-primary)]"><Plus size={16} /></button></div><div className="space-y-2">{form[key].map((item, index) => <div key={index} className="flex gap-2"><input className={inputClass} value={item} onChange={(e) => updateList(key, index, e.target.value)} /><button type="button" onClick={() => update(key, form[key].filter((_, itemIndex) => itemIndex !== index))} className="shrink-0 rounded-lg bg-red-500/10 px-2 text-red-300"><Trash2 size={16} /></button></div>)}</div></div>)}</div></section>
    <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-card)] p-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-black text-white">الأسئلة الشائعة</h2><button type="button" onClick={() => update("faq", [...form.faq, { q: "", a: "" }])} className="flex items-center gap-1 rounded-lg bg-[var(--color-surface)] px-2 py-1.5 text-xs font-bold text-[var(--color-primary)]"><Plus size={15} /> إضافة سؤال</button></div><div className="space-y-3">{form.faq.map((item, index) => <div key={index} className="grid gap-2 rounded-xl bg-[var(--color-surface)] p-3 sm:grid-cols-[1fr_1.5fr_auto]"><input className={inputClass} value={item.q} onChange={(e) => updateFaq(index, "q", e.target.value)} placeholder="السؤال" /><textarea className={inputClass} rows={2} value={item.a} onChange={(e) => updateFaq(index, "a", e.target.value)} placeholder="الإجابة" /><button type="button" onClick={() => update("faq", form.faq.filter((_, itemIndex) => itemIndex !== index))} className="rounded-lg bg-red-500/10 px-2 text-red-300"><Trash2 size={16} /></button></div>)}</div></section>
    <section className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-card)] p-5"><h2 className="mb-4 font-black text-white">ألوان صفحة المواقع</h2><div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center justify-between rounded-xl bg-[var(--color-surface)] p-3 text-sm font-bold text-zinc-300">اللون الأساسي<input type="color" value={form.primaryColor} onChange={(e) => update("primaryColor", e.target.value)} /></label><label className="flex items-center justify-between rounded-xl bg-[var(--color-surface)] p-3 text-sm font-bold text-zinc-300">اللون الثانوي<input type="color" value={form.secondaryColor} onChange={(e) => update("secondaryColor", e.target.value)} /></label></div></section>
    {message && <div className={`rounded-xl p-3 text-sm font-bold ${message.error ? "bg-red-500/10 text-red-300" : "bg-emerald-500/10 text-emerald-300"}`}>{message.text}</div>}<button type="submit" disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--color-primary)] py-3.5 font-black text-black disabled:opacity-50">{saving ? <Loader2 className="animate-spin" size={18} /> : <Save size={18} />} حفظ إعدادات المواقع</button>
  </form></div></DashboardLayout>;
}
